### ISSUE TITLE
ValueError: need more than 2 values to unpack

### ISSUE THREAD

**Issue by snehamurthy21** [YangLab/CIRCexplorer#15]
Start CIRCexplorer 1.1.10
Start to convert fustion reads...
Converted 0 fusion reads!
Start to annotate fusion junctions...
Traceback (most recent call last):
  File "/usr/local/bin/CIRCexplorer.py", line 9, in <module>
    load_entry_point('CIRCexplorer==1.1.10', 'console_scripts', 'CIRCexplorer.py')()
  File "build/bdist.linux-x86_64/egg/circ/CIRCexplorer.py", line 508, in main
    
  File "build/bdist.linux-x86_64/egg/circ/CIRCexplorer.py", line 68, in annotate_fusion
    
  File "build/bdist.linux-x86_64/egg/circ/CIRCexplorer.py", line 209, in parse_ref1
    
ValueError: need more than 2 values to unpack

could someone pls tell me why i am getting 0 fusion reads converted and value error

**Comment by kepbod** [comment]
Please make sure your ref.txt file is in correct format. See [example](https://github.com/YangLab/CIRCexplorer/blob/master/example/ref_example.txt).

**Comment by snehamurthy21** [comment]
yes i used the tools script to generate ref.txt
i still get 0 fusion reads
the value error was solved
thank you

**Comment by kepbod** [comment]
I think it is the problem of your datasets.
