### ISSUE TITLE
unsuccessful installation

### ISSUE THREAD

**Issue by timedreamer** [YangLab/CIRCexplorer#17]
Hi there,

 When I use `pip install CIRCexplorer`, I can install sucessfully. But when I call `CIRCexplorer.py`, i got the following message:

```
Traceback (most recent call last):
  File "/home5/jhuang/software/anaconda3/bin/CIRCexplorer.py", line 7, in <module>
    from circ.CIRCexplorer import main
  File "/home5/jhuang/software/anaconda3/lib/python3.6/site-packages/circ/CIRCexplorer.py", line 31, in <module>
    from genomic_interval import Interval
ModuleNotFoundError: No module named 'genomic_interval'
jhuang@pauper:~/projects/Misc/drought-stress/CIRCexplorer$ CIRCexplorer.py
Traceback (most recent call last):
  File "/home5/jhuang/software/anaconda3/bin/CIRCexplorer.py", line 7, in <module>
    from circ.CIRCexplorer import main
  File "/home5/jhuang/software/anaconda3/lib/python3.6/site-packages/circ/CIRCexplorer.py", line 31, in <module>
    from genomic_interval import Interval
ModuleNotFoundError: No module named 'genomic_interval'
```

When I try to install through conda, I got the following warning that did not success:
```
Fetching package metadata .............
Solving package specifications: .

UnsatisfiableError: The following specifications were found to be in conflict:
  - circexplorer -> python 3.4* -> xz 5.0.5
  - python 3.6*
Use "conda info <package>" to see the dependencies for each package.
``` 

I also tried install from source, but no luck.

Any idea how I can fix?

Thanks in advance!

**Comment by timedreamer** [comment]
I just tried to install in Python 3.4 environment using `conda install circexplorer --channel bioconda`. The installation went well. But still got warnings when I call `CIRCexplorer.py`.

```
Traceback (most recent call last):
  File "/home5/jhuang/software/anaconda3/envs/py34/bin/CIRCexplorer.py", line 9, in <module>
    load_entry_point('CIRCexplorer==1.1.8', 'console_scripts', 'CIRCexplorer.py')()
  File "/home5/jhuang/software/anaconda3/envs/py34/lib/python3.4/site-packages/setuptools-27.2.0-py3.4.egg/pkg_resources/__init__.py", line 565, in load_entry_point
  File "/home5/jhuang/software/anaconda3/envs/py34/lib/python3.4/site-packages/setuptools-27.2.0-py3.4.egg/pkg_resources/__init__.py", line 2598, in load_entry_point
  File "/home5/jhuang/software/anaconda3/envs/py34/lib/python3.4/site-packages/setuptools-27.2.0-py3.4.egg/pkg_resources/__init__.py", line 2258, in load
  File "/home5/jhuang/software/anaconda3/envs/py34/lib/python3.4/site-packages/setuptools-27.2.0-py3.4.egg/pkg_resources/__init__.py", line 2264, in resolve
  File "/home5/jhuang/software/anaconda3/envs/py34/lib/python3.4/site-packages/CIRCexplorer-1.1.8-py3.4.egg/circ/CIRCexplorer.py", line 29, in <module>
  File "/home5/jhuang/software/anaconda3/envs/py34/lib/python3.4/site-packages/pysam/__init__.py", line 5, in <module>
    from pysam.libchtslib import *
ImportError: libhts.so.1: cannot open shared object file: No such file or directory
```

**Comment by xingma** [comment]
It's caused by that CIRCexplorer isn't compatible with python3 and we won't add python3 support to CIRCexplorer. In addition, CIRCexplorer2 has supported python3.

**Comment by timedreamer** [comment]
Thank you. That works. May be add this in the CIRCexplorer documentation?
